### ISSUE TITLE
React Native 0.73 support

### ISSUE THREAD

**Issue by farwayer** [inokawa/react-native-react-bridge#153]
**Describe the bug**
```js
Failed to construct transformer:  Error: Cannot find module 'metro-react-native-babel-transformer'
Require stack:
- .../node_modules/react-native-react-bridge/lib/plugin/index.js
- .../node_modules/metro-transform-worker/src/index.js
```

**To Reproduce**
- Add `react-native-react-bridge/lib/plugin` transformer to metro config

**Expected behavior**
- Bundling without the error

**Platform:**
 - Version of react-native: 0.73.0
 - Version of this package: 0.11.2

**Additional context**

`metro-react-native-babel-transformer` was replaced with `@react-native/metro-babel-transformer` in RN 0.73

**Comment by SolankiYogesh** [comment]
any update ?

**Comment by theprashant-one** [comment]
@farwayer Hi, the message passing is working on 0.73 ?

**Comment by theprashant-one** [comment]
@farwayer Did you get any workaround?
